name: tdl
description: A command-line productivity tool.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  # default
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  args: ^2.0.0
  sqlite3: ^1.0.0
  timeago: ^3.0.1
  path: ^1.7.0
